version: "3.8"

services:
  bot-cril:
    build: ./Bot
    container_name: bot-cril
    env_file:
      - .env
    depends_on:
      - bot-db-cril
    restart: unless-stopped

  bot-db-cril:
    image: postgres:16
    container_name: bot-db-cril
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data_discord:/var/lib/postgresql/data
    ports:
      - ${DB_OUT_PORT}:5432
    restart: unless-stopped

volumes:
  postgres_data_discord:
