version: "3.8"

services:
  discord-bot:
    build: ./Bot
    container_name: discord-bot
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - cril-bot
    restart: always

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data_discord:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - cril-bot
    restart: always

volumes:
  postgres_data_discord:

networks:
  cril-bot:
    external: true
