#!bin/bash

# Launch RefreshSpread.py
echo "Launching RefreshSpread.py"

# Start a timer
START=$(date +%s)

python /home/pi/RefreshSpread.py

# End timer
END=$(date +%s)

# Calculate time taken
DIFF=$(( $END - $START ))

echo "RefreshSpread.py took $DIFF seconds"
echo "activities.json updated !"

