-- POSTGRESQL

CREATE TABLE CURRENT_SPREADSHEETS (
    ID VARCHAR(50),
    ENTRY_DATE TIMESTAMP NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE INSCRIPTIONS_ATELIER (
    ID SERIAL PRIMARY KEY,
    SLOT TIMESTAMP NOT NULL,
    LIEU VARCHAR(255),
    ACTIVITY VARCHAR(255) NOT NULL,
    ACTIVITY_LEVEL VARCHAR(255) NOT NULL,
    LANGUE VARCHAR(255) NOT NULL,
    LASTNAME VARCHAR(255) NOT NULL,
    FIRSTNAME VARCHAR(255) NOT NULL,
    ANG_LEVEL VARCHAR(255),
    ESP_LEVEL VARCHAR(255),
    OBSERVATIONS VARCHAR(4000),
    GROUPE VARCHAR(255)
);


CREATE TABLE INSCRIPTIONS_COACHING (
    ID SERIAL PRIMARY KEY,
    SLOT TIMESTAMP NOT NULL,
    LIEU VARCHAR(255),
    LANGUE VARCHAR(255) NOT NULL,
    LASTNAME VARCHAR(255) NOT NULL,
    FIRSTNAME VARCHAR(255) NOT NULL,
    OBSERVATIONS VARCHAR(4000),
    GROUPE VARCHAR(255),
    COMMENT_COACHING VARCHAR(255)
);
