-- LOGS_ERROR
CREATE TABLE LOGS_ERROR (
    ID SERIAL PRIMARY KEY,
    ENTRY_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ERROR_TYPE VARCHAR(255) NOT NULL,
    STACK_TRACE TEXT NOT NULL,
    MSG VARCHAR(4000) NOT NULL
);

-- LOGS_GENERAL
CREATE TABLE LOGS_GENERAL (
    ID SERIAL PRIMARY KEY,
    ENTRY_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    TYPE VARCHAR(255) NOT NULL,
    MSG VARCHAR(4000) NOT NULL
);

-- COACHING INTERNAL
CREATE TABLE LOGS_COACHING_I (
    ID SERIAL PRIMARY KEY,
    ENTRY_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    USER_ID VARCHAR(20) NOT NULL CHECK (LENGTH(USER_ID) > 17),
    ACTION VARCHAR(255) NOT NULL,
    MSG VARCHAR(4000) NOT NULL
);

-- LOGS_ENTRY
CREATE TABLE LOGS_ENTRY (
    ID SERIAL PRIMARY KEY,
    ENTRY_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    USER_ID VARCHAR(20) NOT NULL CHECK (LENGTH(USER_ID) > 17),
    MSG VARCHAR(4000) NOT NULL
);

-- LOGS_COACHING
CREATE TABLE LOGS_COACHING (
    ID SERIAL PRIMARY KEY,
    ENTRY_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    USER_ID VARCHAR(20) NOT NULL CHECK (LENGTH(USER_ID) > 17),
    MSG VARCHAR(4000) NOT NULL
);
