export enum ButtonId {
  POLL = "POLL_ANSWER_",
  MCQ_ANSWER = "MCQ_ANSWER_",
  COACHING = "COACHING_",
  TOSS_PARTICIPATE = "TOSS_PARTICIPATE",
  TOSS_END = "TOSS_END",
  ENTRY_RENAME = "ENTRY_RENAME",
  LAUNCH_CODE_MODAL = "LAUNCH_CODE_MODAL",
  DONT_HAVE_CODE = "DONT_HAVE_CODE",
  ENTRY_CREATE_THREAD = "ENTRY_CREATE_THREAD",
  START_QUIZZ = "START_QUIZZ",
}
