export enum LogsLevels {
  INFO = "INFO",
  SUCCESS = "SUCCESS",
  SYSTEM = "SYSTEM",
  WARN = "WARN",
  ERROR = "ERROR",
  COACHING = "COACHING",
  COACHINGI = "COACHINGI",
  ENTRY = "ENTRY",
  DPLACE = "DPLACE",
}
