export enum LogsCoachingITypes {
  UPDATE = "UPDATE",
  FETCHING_FILES = "FETCHING_FILES",
  FETCHING_FOLDER = "FETCHING_FOLDER",
  MOOVE = "MOOVE",
  CREATING_FILE = "CREATING_FILE",
  CREATING_DATES_FOLDER = "CREATING_DATES_FOLDER",
}
