name: Deploy Discord Bot

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install
        working-directory: ./Bot

      - name: Build TypeScript
        run: npx tsc
        working-directory: ./Bot

      - name: List files in the build directory
        run: ls -l ./Bot/build

      - name: List files in the node_modules directory
        run: ls -l ./Bot/node_modules

      - name: Create deployment package
        run: zip -r discord-bot-deployment.zip build node_modules package.json
        working-directory: ./Bot

      - name: Deploy to VPS
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          source: discord-bot-deployment.zip
          target: BotCril

      - name: Restart the bot
        run: ssh ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }} "cd /path/to/remote/folder && pm2 restart index.js"
