name: Deploy Discord Bot

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install
        working-directory: ./Bot

      - name: Build TypeScript
        run: npx tsc
        working-directory: ./Bot

      - name: Create deployment package
        run: zip -r discord-bot-deployment.zip ./Bot/build node_modules

      - name: Deploy to VPS
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          source: discord-bot-deployment.zip
          target: BotCril

      - name: SSH to VPS and Configure known_hosts
        run: |
          mkdir -p $HOME/.ssh
          touch $HOME/.ssh/known_hosts
          ssh-keyscan ${{ secrets.VPS_HOST }} >> $HOME/.ssh/known_hosts
          echo "$VPS_HOST $VPS_PUBLIC_KEY" >> $HOME/.ssh/known_hosts
        env:
          VPS_HOST: ${{ secrets.VPS_HOST }}
          VPS_PUBLIC_KEY: ${{ secrets.VPS_PUBLIC_KEY }}

      - name: Unzip the deployment package
        run: ssh -v ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }} "unzip BotCril/discord-bot-deployment.zip -d BotCril"

      - name: Restart the bot
        run: ssh ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }} "cd BotCril && pm2 restart index.js"
