name: Deploy Discord Cril Bot

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install
        working-directory: ./Bot

      - name: Build TypeScript
        run: npx tsc
        working-directory: ./Bot

      - name: Zip deployment package
        run: zip -r discord-bot-deployment.zip ./Bot/build ./Bot/package.json ./Bot/package-lock.json ./Bot/Status.json ./Bot/docs ./Bot/MCQ_Entry.json

      - name: Copy deployment package to VPS
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          source: discord-bot-deployment.zip
          target: BotCril

      - name: Deploy Bot on VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          script: |
            cd BotCril
            rm -r Bot/build
            unzip -o discord-bot-deployment.zip 
            cd Bot
            npm install
            pm2 restart Cril

      - name: Check build status and notify Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          if [ ${{ job.status }} == 'success' ]; then
            curl -H "Content-Type: application/json" -d '{
              "embeds": [{
                "title": "Build Succeeded! :white_check_mark:",
                "color": 65280,
                "description": "A new commit has been pushed to the repository.",
                "fields": [
                  {
                    "name": "Commit Message",
                    "value": "'"$(git log -1 --pretty=%B)"'"
                  }
                ]
              }]
            }' $DISCORD_WEBHOOK
          else
            curl -H "Content-Type: application/json" -d '{
              "embeds": [{
                "title": "Build Failed! :x:",
                "color": 16711680,
                "description": "A new commit has been pushed to the repository.",
                "fields": [
                  {
                    "name": "Commit Message",
                    "value": "'"$(git log -1 --pretty=%B)"'"
                  }
                ]
              }]
            }' $DISCORD_WEBHOOK
          fi
